// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reading struct {
	ID          int64
	StationID   string
	Temperature pgtype.Float8
	Humidity    pgtype.Float8
	RecordedAt  pgtype.Timestamptz
}

type Station struct {
	ID        string
	Name      string
	Location  pgtype.Text
	CreatedAt pgtype.Timestamptz
}
