// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateReading(ctx context.Context, arg CreateReadingParams) (Reading, error)
	CreateStation(ctx context.Context, arg CreateStationParams) (Station, error)
	GetLatestReading(ctx context.Context, stationID string) (Reading, error)
	GetStation(ctx context.Context, id string) (Station, error)
	ListReadingsByStation(ctx context.Context, arg ListReadingsByStationParams) ([]Reading, error)
	ListStations(ctx context.Context) ([]Station, error)
}

var _ Querier = (*Queries)(nil)
