// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReading = `-- name: CreateReading :one
INSERT INTO readings (station_id, temperature, humidity, recorded_at)
VALUES ($1, $2, $3, $4)
RETURNING id, station_id, temperature, humidity, recorded_at
`

type CreateReadingParams struct {
	StationID   string
	Temperature pgtype.Float8
	Humidity    pgtype.Float8
	RecordedAt  pgtype.Timestamptz
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (Reading, error) {
	row := q.db.QueryRow(ctx, createReading,
		arg.StationID,
		arg.Temperature,
		arg.Humidity,
		arg.RecordedAt,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestReading = `-- name: GetLatestReading :one
SELECT id, station_id, temperature, humidity, recorded_at FROM readings
WHERE station_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestReading(ctx context.Context, stationID string) (Reading, error) {
	row := q.db.QueryRow(ctx, getLatestReading, stationID)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Temperature,
		&i.Humidity,
		&i.RecordedAt,
	)
	return i, err
}

const listReadingsByStation = `-- name: ListReadingsByStation :many
SELECT id, station_id, temperature, humidity, recorded_at FROM readings
WHERE station_id = $1
ORDER BY recorded_at DESC
LIMIT $2
`

type ListReadingsByStationParams struct {
	StationID string
	Limit     int32
}

func (q *Queries) ListReadingsByStation(ctx context.Context, arg ListReadingsByStationParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsByStation, arg.StationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Temperature,
			&i.Humidity,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
