// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReading = `-- name: CreateReading :one
INSERT INTO readings (station_id, type, value, recorded_at)
VALUES ($1, $2, $3, $4)
RETURNING id, station_id, type, value, recorded_at
`

type CreateReadingParams struct {
	StationID  string
	Type       ReadingType
	Value      float64
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateReading(ctx context.Context, arg CreateReadingParams) (Reading, error) {
	row := q.db.QueryRow(ctx, createReading,
		arg.StationID,
		arg.Type,
		arg.Value,
		arg.RecordedAt,
	)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Type,
		&i.Value,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestReadingByType = `-- name: GetLatestReadingByType :one
SELECT id, station_id, type, value, recorded_at FROM readings
WHERE station_id = $1 AND type = $2
ORDER BY recorded_at DESC
LIMIT 1
`

type GetLatestReadingByTypeParams struct {
	StationID string
	Type      ReadingType
}

func (q *Queries) GetLatestReadingByType(ctx context.Context, arg GetLatestReadingByTypeParams) (Reading, error) {
	row := q.db.QueryRow(ctx, getLatestReadingByType, arg.StationID, arg.Type)
	var i Reading
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Type,
		&i.Value,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestReadings = `-- name: GetLatestReadings :many
SELECT DISTINCT ON (type) id, station_id, type, value, recorded_at
FROM readings
WHERE station_id = $1
ORDER BY type, recorded_at DESC
`

func (q *Queries) GetLatestReadings(ctx context.Context, stationID string) ([]Reading, error) {
	rows, err := q.db.Query(ctx, getLatestReadings, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Type,
			&i.Value,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsByStation = `-- name: ListReadingsByStation :many
SELECT id, station_id, type, value, recorded_at FROM readings
WHERE station_id = $1
ORDER BY recorded_at DESC
LIMIT $2
`

type ListReadingsByStationParams struct {
	StationID string
	Limit     int32
}

func (q *Queries) ListReadingsByStation(ctx context.Context, arg ListReadingsByStationParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsByStation, arg.StationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Type,
			&i.Value,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsByStationAndType = `-- name: ListReadingsByStationAndType :many
SELECT id, station_id, type, value, recorded_at FROM readings
WHERE station_id = $1 AND type = $2
ORDER BY recorded_at DESC
LIMIT $3
`

type ListReadingsByStationAndTypeParams struct {
	StationID string
	Type      ReadingType
	Limit     int32
}

func (q *Queries) ListReadingsByStationAndType(ctx context.Context, arg ListReadingsByStationAndTypeParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsByStationAndType, arg.StationID, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.Type,
			&i.Value,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
