// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stations.sql

package database

import (
	"context"
)

const createStation = `-- name: CreateStation :one
INSERT INTO stations (id, name, latitude, longitude)
VALUES ($1, $2, $3, $4)
RETURNING id, name, latitude, longitude, created_at
`

type CreateStationParams struct {
	ID        string
	Name      string
	Latitude  float64
	Longitude float64
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, createStation,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
	)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const getStation = `-- name: GetStation :one
SELECT id, name, latitude, longitude, created_at FROM stations
WHERE id = $1
`

func (q *Queries) GetStation(ctx context.Context, id string) (Station, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const listStations = `-- name: ListStations :many
SELECT id, name, latitude, longitude, created_at FROM stations
ORDER BY created_at DESC
`

func (q *Queries) ListStations(ctx context.Context) ([]Station, error) {
	rows, err := q.db.Query(ctx, listStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStation = `-- name: UpsertStation :one
INSERT INTO stations (id, name, latitude, longitude)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, latitude, longitude, created_at
`

type UpsertStationParams struct {
	ID        string
	Name      string
	Latitude  float64
	Longitude float64
}

func (q *Queries) UpsertStation(ctx context.Context, arg UpsertStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, upsertStation,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
	)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}
