// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStation = `-- name: CreateStation :one
INSERT INTO stations (id, name, location)
VALUES ($1, $2, $3)
RETURNING id, name, location, created_at
`

type CreateStationParams struct {
	ID       string
	Name     string
	Location pgtype.Text
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, createStation, arg.ID, arg.Name, arg.Location)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getStation = `-- name: GetStation :one
SELECT id, name, location, created_at FROM stations
WHERE id = $1
`

func (q *Queries) GetStation(ctx context.Context, id string) (Station, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listStations = `-- name: ListStations :many
SELECT id, name, location, created_at FROM stations
ORDER BY created_at DESC
`

func (q *Queries) ListStations(ctx context.Context) ([]Station, error) {
	rows, err := q.db.Query(ctx, listStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
